// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// armadillo_lm_local_cv
Rcpp::List armadillo_lm_local_cv(arma::vec& y, arma::mat& x0, arma::mat& X0, arma::mat& x, arma::mat& X, Rcpp::List& H_values, int k_fold);
RcppExport SEXP _armadilLocalregression_armadillo_lm_local_cv(SEXP ySEXP, SEXP x0SEXP, SEXP X0SEXP, SEXP xSEXP, SEXP XSEXP, SEXP H_valuesSEXP, SEXP k_foldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type H_values(H_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type k_fold(k_foldSEXP);
    rcpp_result_gen = Rcpp::wrap(armadillo_lm_local_cv(y, x0, X0, x, X, H_values, k_fold));
    return rcpp_result_gen;
END_RCPP
}
// armadillo_lm
arma::vec armadillo_lm(arma::mat& X, arma::vec& y);
RcppExport SEXP _armadilLocalregression_armadillo_lm(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(armadillo_lm(X, y));
    return rcpp_result_gen;
END_RCPP
}
// armadillo_lm_local
arma::vec armadillo_lm_local(arma::vec& y, arma::mat& x0, arma::mat& X0, arma::mat& x, arma::mat& X, arma::mat& H);
RcppExport SEXP _armadilLocalregression_armadillo_lm_local(SEXP ySEXP, SEXP x0SEXP, SEXP X0SEXP, SEXP xSEXP, SEXP XSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(armadillo_lm_local(y, x0, X0, x, X, H));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_armadilLocalregression_armadillo_lm_local_cv", (DL_FUNC) &_armadilLocalregression_armadillo_lm_local_cv, 7},
    {"_armadilLocalregression_armadillo_lm", (DL_FUNC) &_armadilLocalregression_armadillo_lm, 2},
    {"_armadilLocalregression_armadillo_lm_local", (DL_FUNC) &_armadilLocalregression_armadillo_lm_local, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_armadilLocalregression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
