# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform k-fold cross-validation for the bandwidth matrix H
#'
#' @description This function performs k-fold cross-validation for the bandwidth matrix \eqn{\mathbf{H}} in a local regression model using a Gaussian kernel.
#'
#' @param y Output variable
#' @param x0 Matrix of the predictor variables at a single prediction location
#' @param X0 Matrix of all the covariates at the prediction location
#' @param x Matrix of the predictor variables
#' @param X Matrix of all the covariates
#' @param H_values List of candidate bandwidth matrices
#' @param k_fold Number of folds for cross-validation
#'
#' @return A list containing the selected bandwidth matrix \eqn{\mathbf{H}} and the fitted values using that bandwidth matrix.
#' @export
armadillo_cv_H <- function(y, x0, X0, x, X, H_values, k_fold) {
    .Call(`_armadilLocalregression_armadillo_lm_local_cv`, y, x0, X0, x, X, H_values, k_fold)
}

#' Evaluate multivariate Gaussian density
#'
#' @description Analogous to the `dmvnorm` function in the `mvtnorm` package.
#'
#' @param X matrix of quantiles
#' @param mu vector of means
#' @param L lower triangular matrix of the Cholesky decomposition of the covariance matrix
#'
#' @return vector of density values
NULL

#' Linear regression using QR decomposition
#'
#' @description Fit a linear regression model with `RcppArmadillo` using QR decomposition.
#'
#' @param X Model matrix of dimension n x p
#' @param y Response vector of length n
#'
#' @return Coefficients of the linear model
#' @export
#'
#' @examples
#' data(mtcars)
#' y <- mtcars$mpg
#' X <- with(mtcars, cbind(1, wt, wt^2, hp, hp^2))
#' beta_hat <- armadillo_lm(X, y)
#' beta_hat
armadillo_lm <- function(X, y) {
    .Call(`_armadilLocalregression_armadillo_lm`, X, y)
}

#' Local regression model
#'
#' @description This function is used to fit a local regression model with Gaussian kernel weights using `RcppArmadillo`.
#' For a given \eqn{\mathbf{x}_0}, this function estimates \eqn{\hat{\beta}(\mathbf{x}_0)}, such that
#' \deqn{\hat{\beta}(\mathbf{x}_0) = \arg\min_{\beta} \sum_{i=1}^n \kappa_{\mathbf{H}}(\mathbf{x}_0 - \mathbf{x}_i) (y_i - \tilde{\mathbf{x}}_i^\top \beta)^2}
#' where \eqn{\kappa_H} is a density kernel with positive definite bandwidth matrix \eqn{\mathbf{H}}.
#'
#' @param y Output variable
#' @param x0 Matrix of the predictor variables at a single prediction location
#' @param X0 Matrix of all the covariates at the prediction location
#' @param x Matrix of the predictor variables
#' @param X Matrix of all the covariates
#' @param H Positive definite bandwidth matrix
#'
#' @return The estimated regression coefficients \eqn{\hat \beta(\mathbf{x}_0)} at the prediction locations
#' @export
#'
#' @examples
#' data(mtcars)
#' y <- mtcars$mpg
#' x <- as.matrix(mtcars[, c("wt", "hp")])
#' X <- with(mtcars, cbind(1, wt, wt^2, hp, hp^2))
#' H <- diag(2) # use identity bandwidth matrix for example
#' # Predict at three locations
#' preds <- armadillo_lm_local(y= y, x0 = x[1:3,], X0 = X[1:3,], x = x, X = X, H = H)
armadillo_lm_local <- function(y, x0, X0, x, X, H) {
    .Call(`_armadilLocalregression_armadillo_lm_local`, y, x0, X0, x, X, H)
}

